# Generated by Django 5.0 on 2023-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=4.0, verbose_name='Создан'),
            preserve_default=False,
        ),
    ]
